### ISSUE TITLE
linebreak is trimmed

### ISSUE THREAD

**Issue by Zane-XY** [samskivert/jmustache#126] opened 2020-12-14 05:18 UTC
Trying to modify the template in the swagger code generator. The template is like

```mustache
{{#useBeanValidation}}{{>beanValidation}}{{/useBeanValidation}}
  public {{{datatypeWithEnum}}} {{getter}}() {
    return {{name}};
  }
```
the expected result is 

```java
  @Min(1) @Max(99999)
  public Integer getZip() {
    return zip;
  }
```

however this gives 

```java
 @Min(1) @Max(99999)  public Integer getZip() {
    return zip;
  }
```
the line break after `{{/useBeanValidation}}` is not preserved.

**Comment by agentgt** [comment] 2022-04-05 22:21
First see this: https://github.com/samskivert/jmustache#newline-trimming

Second I could not reproduce your problem.

```java
     @Test
    public void testTrim()
            throws Exception {
        String template = //
                """
                        {{#useBeanValidation}}{{> beanValidation}}{{/useBeanValidation}}
                        public Integer getZip() {
                          return zip;
                        }""";
        
        var m = Map.of("useBeanValidation", true, "beanValidation", "@Validation");
        
        StringReader sr = new StringReader("@Min(1) @Max(99999)");
        Mustache.TemplateLoader loader = name -> sr;
        
        String actual = Mustache.compiler()
                .withLoader(loader)
                .compile(template).execute(m);
        
        String expected = "@Min(1) @Max(99999)\n" //  notice new line
                + "public Integer getZip() {\n"
                + "  return zip;\n"
                + "}";
        
        assertEquals(expected, actual);
    }
```

**Comment by agentgt** [comment] 2023-12-04 16:13
@samskivert 

I could not reproduce this. I think we can close this issue.

**Closed** 2023-12-05 05:08 UTC
